"""Fixed user profile table

Revision ID: 204e934b5d5d
Revises: 8f7de9aa1dd1
Create Date: 2024-06-11 11:13:39.062925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '204e934b5d5d'
down_revision: Union[str, None] = '8f7de9aa1dd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfiles', sa.Column('password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfiles', 'password')
    # ### end Alembic commands ###
