"""remove access token from user model

Revision ID: 3820d23691b7
Revises: 204e934b5d5d
Create Date: 2024-09-05 14:35:49.925596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3820d23691b7'
down_revision: Union[str, None] = '204e934b5d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfiles', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfiles', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
