"""New fields in User

Revision ID: 9f41a429e374
Revises: 2394a9b5b8b8
Create Date: 2024-09-06 16:02:52.783877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f41a429e374'
down_revision: Union[str, None] = '2394a9b5b8b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfiles', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('UserProfiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('UserProfiles', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfiles', 'name')
    op.drop_column('UserProfiles', 'email')
    op.drop_column('UserProfiles', 'google_access_token')
    # ### end Alembic commands ###
