"""upd UserProfile

Revision ID: ae7efcb2c3e7
Revises: 9f41a429e374
Create Date: 2024-09-06 16:16:06.309287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7efcb2c3e7'
down_revision: Union[str, None] = '9f41a429e374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('UserProfiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('UserProfiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('UserProfiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
