"""Added yandex access token

Revision ID: c35e5221f5d8
Revises: ae7efcb2c3e7
Create Date: 2024-09-13 11:26:26.208715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c35e5221f5d8'
down_revision: Union[str, None] = 'ae7efcb2c3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('UserProfiles', sa.Column('yandex_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('UserProfiles', 'yandex_access_token')
    # ### end Alembic commands ###
